### PR TITLE
Update Catch2 to v2.13.10

### LINKED ISSUE #124: Catch2 version is too old for glibc >= 2.34
Hello,

compilation of the first example with `hipsycl` and clang version 13 fails with [this output](https://github.com/codeplaysoftware/syclacademy/files/8457097/compile_output.txt).
This seems to be caused by a bug in Catch2 (see catchorg/Catch2#2178) that has already been fixed, so updating the Catch2 submodule to newer commit should fix this.

Cheers,
Nils

### PR DESCRIPTION
**Pull request by rafbiels**
Fix #124 by updating the Catch2 submodule to tag v2.13.10 where it has been already solved

### CODE REVIEW

**Comment by hdelan** [comment]
LGTM. Trusting that the exercises still work? Also it would be nice if we broke this dependency on Catch2. I think having a testing lib (albeit header only) is overkill for syclacademy

**Review by AerialMantis — APPROVED** [review]
LGTM, thanks!

**Comment by rafbiels** [comment]
Thanks @hdelan and @AerialMantis!

> Trusting that the exercises still work? 

On Intel DevCloud with Ubuntu 20.04.5 and oneAPI 2023.0.0 exercises 1-14 work out of the box, as tested with:
```sh
for NUM in $(seq -f %02.0f 14); do icpx -fsycl -I../src/External/Catch2/single_include -o sycl-ex-$NUM ../src/Code_Exercises/Exercise_${NUM}*/solution.cpp && ./sycl-ex-$NUM; done
```
There is no regression with this PR, the outcome of the above is identical.

> Also it would be nice if we broke this dependency on Catch2. I think having a testing lib (albeit header only) is overkill for syclacademy

I would agree, especially since Catch2 is no longer header-only since v3 and I'm not sure how long v2 will be maintained. Until we change that, this PR at least makes syclacademy usable on Ubuntu 22.04.

**Comment by hdelan** [comment]
Nice one!

**Comment by alexschroeter** [comment]
Thank you for the quick response. I can confirm the tests on Ubuntu 22.04.1 LTS now pass. Exercise 5 failing is because I don't have an Intel GPU but it works when I ask for my vendor.

```
(base) aschroeter@asustest04:~/syclacademy$ for NUM in $(seq -f %02.0f 14); do ~/hipsyclbuild/bin/syclcc -O3 --hipsycl-targets='omp;hip:gfx906' -I./External/Catch2/single_include -o sycl-ex-$NUM ./Code_Exercises/Exercise_${NUM}*/solution.cpp && HIP_VISIBLE_DEVICES=0,1 ./sycl-ex-$NUM; done
===============================================================================
All tests passed (1 assertion in 1 test case)

./Code_Exercises/Exercise_02_Hello_World/solution.cpp:29:49: warning: 'operator<<' is deprecated: sycl::stream in hipSYCL requires backend printf() support, printf is however still experimental in AMD ROCm when compiling with clang. Define HIPSYCL_EXPERIMENTAL_ROCM_PRINTF to attempt to use it. Otherwise, uses of the stream class will be transformed into no operations. [-Wdeprecated-declarations]
        cgh.single_task<hello_world>([=]() { os << "Hello World!\n"; });
                                                ^
/home/aschroeter/hipsyclbuild/bin/../include/SYCL/../hipSYCL/sycl/libkernel/stream.hpp:111:15: note: 'operator<<' has been explicitly marked deprecated here
const stream& operator<<(const stream& os, T v) {
              ^
./Code_Exercises/Exercise_02_Hello_World/solution.cpp:29:49: warning: 'operator<<<const char *>' is deprecated: sycl::stream in hipSYCL requires backend printf() support, printf is however still experimental in AMD ROCm when compiling with clang. Define HIPSYCL_EXPERIMENTAL_ROCM_PRINTF to attempt to use it. Otherwise, uses of the stream class will be transformed into no operations. [-Wdeprecated-declarations]
        cgh.single_task<hello_world>([=]() { os << "Hello World!\n"; });
                                                ^
/home/aschroeter/hipsyclbuild/bin/../include/SYCL/../hipSYCL/sycl/libkernel/stream.hpp:106:3: note: 'operator<<<const char *>' has been explicitly marked deprecated here
[[deprecated("sycl::stream in hipSYCL requires backend printf() support, "
  ^
2 warnings generated when compiling for gfx906.
===============================================================================
All tests passed (1 assertion in 1 test case)

===============================================================================
All tests passed (2 assertions in 2 test cases)

===============================================================================
All tests passed (1 assertion in 1 test case)

Exception caught: No matching device

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sycl-ex-05 is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
intel_gpu_device_selector
-------------------------------------------------------------------------------
./Code_Exercises/Exercise_05_Device_Selection/solution.cpp:58
...............................................................................

./Code_Exercises/Exercise_05_Device_Selection/solution.cpp:92: FAILED:
  REQUIRE( r == 42 )
with expansion:
  0 == 42

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

===============================================================================
All tests passed (1024 assertions in 1 test case)

===============================================================================
All tests passed (1 assertion in 1 test case)

===============================================================================
All tests passed (1024 assertions in 1 test case)

===============================================================================
All tests passed (6144 assertions in 6 test cases)

===============================================================================
All tests passed (2048 assertions in 2 test cases)

===============================================================================
All tests passed (2048 assertions in 2 test cases)

[hipSYCL Warning] dag_direct_scheduler: Detected a requirement that is neither of discard access mode (SYCL 1.2.1) nor noinit property (SYCL 2020) that accesses uninitialized data. Consider changing to discard/noinit. Optimizing potential data transfers away.
[hipSYCL Warning] dag_direct_scheduler: Detected a requirement that is neither of discard access mode (SYCL 1.2.1) nor noinit property (SYCL 2020) that accesses uninitialized data. Consider changing to discard/noinit. Optimizing potential data transfers away.
===============================================================================
All tests passed (2048 assertions in 2 test cases)

Running on devices:
1:      AMD Radeon VII
2:
===============================================================================
All tests passed (1024 assertions in 1 test case)

===============================================================================
All tests passed (2048 assertions in 2 test cases)
```

**Pull request merged**
