### PR TITLE
Restructure lessons and exercises for IWOCL23, fix issues

### PR DESCRIPTION
**Pull request by igorvorobtsov**
- Removed unused lessons and renamed left topics
- Updated main README.md
- Checked all exercises on DevCloud and fixed issues in Exercise_05_Image_Convolution (wrong path to the image) and Exercise_04_SYCL_Reduction (wg=1024 is not supported by integrated graphics)
- Generated new pdf versions for all presentation

### CODE REVIEW

**Comment by keryell** [comment]
I am unsure it is a good idea.
Then the student can no longer look at the other lessons or exercises to know how to do things missing from the official lessons.
It becomes impossible to merge this into `main` branch for the next tutorials.

**Review by rodburns — APPROVED** [review]
LGTM

**Comment by igorvorobtsov** [comment]
> I am unsure it is a good idea.
> Then the student can no longer look at the other lessons or exercises to know how to do things missing from the official lessons.
> It becomes impossible to merge this into `main` branch for the next tutorials.

Well, we did it last time for IWOCL22 (check the branch iwocl22). There are pros and cons to do that. For attendees it looks more adopted for the event and not so confusing. There is always a link to the main branch with all exercises and the explanation on main Readme page to go there for more details and lectures.
There are also instructions there to check Readme file for each exercise.
There is a command to compile the code with DPC++ in each exercises Readme file.

Note that we haven’t checked all lessons and exercises from main branch. Some may be outdated. I only updated lessons and exercises we need for this event.
Definitely more efforts required to update a main branch, but the new structured doesn’t block it - just makes not so simple. I will need to do more manual work.
In fact this restructuring also took quite a while for me.

**Review by keryell — APPROVED** [review]
OK, your approach makes sense too.
Thanks.

**Comment by rodburns** [comment]
@igorvorobtsov some other PRs have caused conflicts. Do you prefer to resolve them in this PR or revert the others and merge them afterwards?

**Comment by igorvorobtsov** [comment]
> @igorvorobtsov some other PRs have caused conflicts. Do you prefer to resolve them in this PR or revert the others and merge them afterwards?

It will be easier to merge other PRs afterwards.

**Pull request merged**
